# Generated by Django 4.2.20 on 2025-03-25 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.TextField()),
                ("optionA", models.CharField(max_length=255)),
                ("optionB", models.CharField(max_length=255)),
                ("optionC", models.CharField(max_length=255)),
                ("optionD", models.CharField(max_length=255)),
                ("correctAnswer", models.CharField(max_length=255)),
                ("difficulty", models.CharField(max_length=255)),
                ("topic", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("firstName", models.CharField(max_length=50)),
                ("lastName", models.CharField(max_length=50)),
                ("emailAddress", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=20)),
                ("isVerified", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("firstName", models.CharField(max_length=50)),
                ("lastName", models.CharField(max_length=50)),
                ("emailAddress", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=20)),
                ("isVerified", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quiz", models.DecimalField(decimal_places=2, max_digits=5)),
                ("coding", models.DecimalField(decimal_places=2, max_digits=5)),
                ("behaviour", models.DecimalField(decimal_places=2, max_digits=5)),
                ("isCaught", models.BooleanField(default=False)),
                ("result", models.CharField(max_length=255)),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exam.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quizName", models.CharField(max_length=255)),
                ("CodingQuestion", models.TextField()),
                ("BehaviourQuestion", models.TextField()),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exam.student"
                    ),
                ),
            ],
        ),
    ]
