# Generated by Django 4.2.20 on 2025-03-25 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0006_behavioralquestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultGraph",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quizQuestions",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "quizMarks",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("codingQuestion", models.TextField(blank=True, default="", null=True)),
                (
                    "codingMarks",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "behaviourQuestion",
                    models.TextField(blank=True, default="", null=True),
                ),
                (
                    "behaviourMarks",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("isCaught", models.BooleanField(default=False)),
                (
                    "result",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exam.student"
                    ),
                ),
            ],
        ),
    ]
